### ISSUE TITLE
IP.BIN?

### ISSUE THREAD

**Issue by RetroGameTalk** [Sappharad/GDIbuilder#1]
Hello, where does one is supposed to get IP.BIN?
Is it different for every game? Sorry not an expert.

Thanks.

**Comment by Sappharad** [comment]
It's part of the game data. Just extract it from the game you're rebuilding using something like GD-ROM Explorer.

Yes, it's different for every game. It contains information about the primary executable to load, the type of game, the region, peripherals supported, (controllers, VGA box, etc.) and even the list of CDDA tracks when applicable.
